# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculation_pb2 as calculation__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformTotalCalculation = channel.unary_unary(
                '/CalculationService/PerformTotalCalculation',
                request_serializer=calculation__pb2.CalculationRequest.SerializeToString,
                response_deserializer=calculation__pb2.CalculationResponse.FromString,
                _registered_method=True)


class CalculationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PerformTotalCalculation(self, request, context):
        """Método para el cliente que inicia la solicitud de cálculo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformTotalCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformTotalCalculation,
                    request_deserializer=calculation__pb2.CalculationRequest.FromString,
                    response_serializer=calculation__pb2.CalculationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CalculationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CalculationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformTotalCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CalculationService/PerformTotalCalculation',
            calculation__pb2.CalculationRequest.SerializeToString,
            calculation__pb2.CalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformPartialCalculation = channel.unary_unary(
                '/OperationService/PerformPartialCalculation',
                request_serializer=calculation__pb2.PartialCalculationRequest.SerializeToString,
                response_deserializer=calculation__pb2.PartialCalculationResponse.FromString,
                _registered_method=True)


class OperationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PerformPartialCalculation(self, request, context):
        """Métodos para cada servidor de operación que hacen cálculos parciales
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformPartialCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformPartialCalculation,
                    request_deserializer=calculation__pb2.PartialCalculationRequest.FromString,
                    response_serializer=calculation__pb2.PartialCalculationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OperationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OperationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformPartialCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OperationService/PerformPartialCalculation',
            calculation__pb2.PartialCalculationRequest.SerializeToString,
            calculation__pb2.PartialCalculationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
