# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calculation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculation.proto\"8\n\x12\x43\x61lculationRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x01\x12\x10\n\x08operand2\x18\x02 \x01(\x01\"%\n\x13\x43\x61lculationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\"*\n\x19PartialCalculationRequest\x12\r\n\x05value\x18\x01 \x01(\x01\"4\n\x1aPartialCalculationResponse\x12\x16\n\x0epartial_result\x18\x01 \x01(\x01\x32Z\n\x12\x43\x61lculationService\x12\x44\n\x17PerformTotalCalculation\x12\x13.CalculationRequest\x1a\x14.CalculationResponse2h\n\x10OperationService\x12T\n\x19PerformPartialCalculation\x12\x1a.PartialCalculationRequest\x1a\x1b.PartialCalculationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATIONREQUEST']._serialized_start=21
  _globals['_CALCULATIONREQUEST']._serialized_end=77
  _globals['_CALCULATIONRESPONSE']._serialized_start=79
  _globals['_CALCULATIONRESPONSE']._serialized_end=116
  _globals['_PARTIALCALCULATIONREQUEST']._serialized_start=118
  _globals['_PARTIALCALCULATIONREQUEST']._serialized_end=160
  _globals['_PARTIALCALCULATIONRESPONSE']._serialized_start=162
  _globals['_PARTIALCALCULATIONRESPONSE']._serialized_end=214
  _globals['_CALCULATIONSERVICE']._serialized_start=216
  _globals['_CALCULATIONSERVICE']._serialized_end=306
  _globals['_OPERATIONSERVICE']._serialized_start=308
  _globals['_OPERATIONSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
